name: qmb
channels:
#  - hexrd
  - conda-forge
#  - defaults
dependencies:
  - python>=3.9,<3.11
  - fabio==0.14.0
  - hdf5==1.12.1
  - hdf5plugin==3.3.1
  - json5==0.9.5
  - matplotlib==3.5.2 #
  - matplotlib-base==3.5.2
  - matplotlib-inline==0.1.3
  - nexpy==0.14.5
  - nexusformat==0.7.6 # can be updated?
  - numpy==1.23.5
  - pyfai==0.21.3
  - pillow==9.2.0 # provides PIL
  - spec2nexus==2021.2.1
  - scipy==1.7.3

